In [1]:
import pandas as pd
df = pd.read_csv('baseGamesAndOdds.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16979 entries, 0 to 16978
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              16979 non-null  int64
 1   GAME_DATE_EST   16979 non-null  object
 2   GAME_ID         16979 non-null  int64
 3   SEASON          16979 non-null  int64
 4   HOME_TEAM_ID    16979 non-null  int64
 5   HOME_W%         16979 non-null  float64
 6   AWAY_TEAM_ID    16979 non-null  int64
 7   AWAY_W%         16979 non-null  float64
 8   SPREAD          8602 non-null   float64
 9   HOME_TEAM_WINS  16979 non-null  int64
 10  MARGIN          16979 non-null  float64
dtypes: float64(4), int64(6), object(1)
memory usage: 1.4+ MB

In [2]:
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

## Algo: Choose team with highest current win %

In [3]:
df['W%_PRED'] = np.where(df['HOME_W%'] >= df["AWAY_W%"], True, False).astype("int32")
df.head()

,ID,GAME_DATE_EST,GAME_ID,SEASON,HOME_TEAM_ID,HOME_W%,AWAY_TEAM_ID,AWAY_W%,SPREAD,HOME_TEAM_WINS,MARGIN,W%_PRED
0,0,2019-04-10,21801220,2018,1610612737,0.354,1610612754,0.585,-5.25,0,-1.0,0
1,1,2019-04-10,21801221,2018,1610612751,0.512,1610612748,0.476,-4.58,1,19.0,1
2,2,2019-04-10,21801222,2018,1610612766,0.476,1610612753,0.512,-3.50,0,-8.0,0
3,3,2019-04-10,21801223,2018,1610612752,0.207,1610612765,0.500,8.58,0,-26.0,0
4,4,2019-04-10,21801224,2018,1610612755,0.622,1610612741,0.268,-6.42,1,16.0,1

In [4]:
y_actual = df['HOME_TEAM_WINS']
y_pred_algo = df['W%_PRED']

# confusion matrix
print(confusion_matrix(y_actual, y_pred_algo))

# accuracy: (tp + tn) / (p + n)
print('Accuracy: %f' % accuracy_score(y_actual, y_pred_algo))

# precision tp / (tp + fp)
print('Precision: %f' % precision_score(y_actual, y_pred_algo))

# recall: tp / (tp + fn)
print('Recall: %f' % recall_score(y_actual, y_pred_algo))

[[5091 1822]
 [3058 7008]]
Accuracy: 0.712586
Precision: 0.793658
Recall: 0.696205

## Algo: Choose team that vegas chooses

In [5]:
# Removing all rows without the SPREAD variable
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8602 entries, 0 to 8608
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              8602 non-null   int64
 1   GAME_DATE_EST   8602 non-null   object
 2   GAME_ID         8602 non-null   int64
 3   SEASON          8602 non-null   int64
 4   HOME_TEAM_ID    8602 non-null   int64
 5   HOME_W%         8602 non-null   float64
 6   AWAY_TEAM_ID    8602 non-null   int64
 7   AWAY_W%         8602 non-null   float64
 8   SPREAD          8602 non-null   float64
 9   HOME_TEAM_WINS  8602 non-null   int64
 10  MARGIN          8602 non-null   float64
 11  W%_PRED         8602 non-null   int32
dtypes: float64(4), int32(1), int64(6), object(1)
memory usage: 840.0+ KB

In [6]:
df['VEGAS_PRED'] = np.where((df['SPREAD'] <= 0), True, False).astype("int32")
df.head(50)

,ID,GAME_DATE_EST,GAME_ID,SEASON,HOME_TEAM_ID,HOME_W%,AWAY_TEAM_ID,AWAY_W%,SPREAD,HOME_TEAM_WINS,MARGIN,W%_PRED,VEGAS_PRED
0,0,2019-04-10,21801220,2018,1610612737,0.354,1610612754,0.585,-5.25,0,-1.0,0,1
1,1,2019-04-10,21801221,2018,1610612751,0.512,1610612748,0.476,-4.58,1,19.0,1,1
2,2,2019-04-10,21801222,2018,1610612766,0.476,1610612753,0.512,-3.50,0,-8.0,0,1
3,3,2019-04-10,21801223,2018,1610612752,0.207,1610612765,0.500,8.58,0,-26.0,0,0
4,4,2019-04-10,21801224,2018,1610612755,0.622,1610612741,0.268,-6.42,1,16.0,1,1
5,5,2019-04-10,21801225,2018,1610612763,0.402,1610612744,0.695,5.42,1,15.0,0,0
6,6,2019-04-10,21801226,2018,1610612749,0.732,1610612760,0.598,4.08,0,-11.0,1,0
7,7,2019-04-10,21801227,2018,1610612759,0.585,1610612742,0.402,-14.00,1,11.0,1,1
8,8,2019-04-10,21801228,2018,1610612743,0.659,1610612750,0.439,-12.67,1,4.0,1,1
9,9,2019-04-10,21801229,2018,1610612746,0.585,1610612762,0.610,-7.33,1,6.0,0,1
10,10,2019-04-10,21801230,2018,1610612757,0.646,1610612758,0.476,-3.67,1,5.0,1,1
11,11,2019-04-09,21801209,2018,1610612739,0.232,1610612766,0.481,8.25,0,-27.0,0,0
12,12,2019-04-09,21801210,2018,1610612765,0.494,1610612763,0.395,-11.25,1,7.0,1,1
13,13,2019-04-09,21801211,2018,1610612764,0.390,1610612738,0.598,-5.00,0,-6.0,0,1
14,14,2019-04-09,21801212,2018,1610612748,0.481,1610612755,0.617,-5.92,1,23.0,0,1
15,15,2019-04-09,21801213,2018,1610612741,0.272,1610612752,0.210,-1.83,0,-10.0,1,1
16,16,2019-04-09,21801214,2018,1610612750,0.444,1610612761,0.707,7.33,0,-20.0,0,0
17,17,2019-04-09,21801215,2018,1610612740,0.402,1610612744,0.704,9.67,0,-9.0,0,0
18,18,2019-04-09,21801216,2018,1610612742,0.407,1610612756,0.232,-8.33,1,11.0,1,1
19,19,2019-04-09,21801217,2018,1610612762,0.617,1610612743,0.654,-2.08,1,10.0,0,1
20,20,2019-04-09,21801218,2018,1610612760,0.593,1610612745,0.646,2.75,1,1.0,0,0
21,21,2019-04-09,21801219,2018,1610612747,0.451,1610612757,0.642,9.67,0,-3.0,0,0
22,22,2019-04-07,21801195,2018,1610612761,0.704,1610612748,0.475,-5.58,1,8.0,1,1
23,23,2019-04-07,21801196,2018,1610612739,0.235,1610612759,0.580,8.67,0,-22.0,0,0
24,24,2019-04-07,21801197,2018,1610612750,0.450,1610612760,0.588,6.25,0,-6.0,0,0
25,25,2019-04-07,21801198,2018,1610612765,0.488,1610612766,0.475,-6.58,0,-13.0,1,1
26,26,2019-04-07,21801199,2018,1610612754,0.580,1610612751,0.506,-2.92,0,-12.0,1,1
27,27,2019-04-07,21801201,2018,1610612763,0.400,1610612742,0.400,0.50,0,-2.0,1,0
28,28,2019-04-07,21801200,2018,1610612745,0.654,1610612756,0.235,-18.50,1,36.0,1,1
29,29,2019-04-07,21801202,2018,1610612749,0.741,1610612737,0.358,-11.33,1,8.0,1,1
30,30,2019-04-07,21801203,2018,1610612738,0.593,1610612753,0.506,-4.17,0,-8.0,1,1
31,31,2019-04-07,21801204,2018,1610612752,0.200,1610612764,0.395,4.00,1,3.0,0,0
32,32,2019-04-07,21801205,2018,1610612744,0.700,1610612746,0.580,-11.08,1,27.0,1,1
33,33,2019-04-07,21801206,2018,1610612757,0.638,1610612743,0.663,-7.42,1,7.0,0,1
34,34,2019-04-07,21801207,2018,1610612758,0.481,1610612740,0.407,-11.42,0,-4.0,1,1
35,35,2019-04-07,21801208,2018,1610612747,0.457,1610612762,0.613,11.92,1,4.0,0,0
36,36,2019-04-06,21801193,2018,1610612749,0.738,1610612751,0.500,-4.00,0,-5.0,1,1
37,37,2019-04-06,21801194,2018,1610612741,0.275,1610612755,0.625,10.08,0,-20.0,0,0
38,38,2019-04-05,21801180,2018,1610612766,0.468,1610612761,0.700,5.75,1,2.0,0,0
39,39,2019-04-05,21801181,2018,1610612753,0.500,1610612737,0.363,-8.75,1,36.0,1,1
40,40,2019-04-05,21801182,2018,1610612764,0.400,1610612759,0.575,6.50,0,-17.0,0,0
41,41,2019-04-05,21801183,2018,1610612754,0.588,1610612738,0.600,1.25,0,-20.0,0,0
42,42,2019-04-05,21801184,2018,1610612745,0.650,1610612752,0.190,-17.92,1,24.0,1,1
43,43,2019-04-05,21801185,2018,1610612750,0.456,1610612748,0.481,3.67,1,2.0,0,0
44,44,2019-04-05,21801186,2018,1610612760,0.582,1610612765,0.494,-6.40,1,13.0,1,1
45,45,2019-04-05,21801187,2018,1610612742,0.392,1610612763,0.405,-4.00,0,-10.0,0,1
46,46,2019-04-05,21801188,2018,1610612762,0.620,1610612758,0.488,-10.08,1,21.0,1,1
47,47,2019-04-05,21801189,2018,1610612756,0.238,1610612740,0.400,2.50,1,7.0,0,0
48,48,2019-04-05,21801190,2018,1610612743,0.671,1610612757,0.633,-6.20,1,9.0,1,1
49,49,2019-04-05,21801191,2018,1610612744,0.696,1610612739,0.238,-16.00,1,6.0,1,1

In [7]:
y_actual = df['HOME_TEAM_WINS']
y_pred_algo = df['VEGAS_PRED']

# confusion matrix
print(confusion_matrix(y_actual, y_pred_algo))

# accuracy: (tp + tn) / (p + n)
print('Accuracy: %f' % accuracy_score(y_actual, y_pred_algo))

# precision tp / (tp + fp)
print('Precision: %f' % precision_score(y_actual, y_pred_algo))

# recall: tp / (tp + fn)
print('Recall: %f' % recall_score(y_actual, y_pred_algo))

[[1886 1666]
 [1031 4019]]
Accuracy: 0.686468
Precision: 0.706948
Recall: 0.795842

## Adding column for if home team beats spread
- Potentially another classification target?

In [8]:
df['HOME_TEAM_BEATS_SPREAD'] = np.where((df['MARGIN'] > -df['SPREAD']), True, False).astype("int32")
df.head(50)

,ID,GAME_DATE_EST,GAME_ID,SEASON,HOME_TEAM_ID,HOME_W%,AWAY_TEAM_ID,AWAY_W%,SPREAD,HOME_TEAM_WINS,MARGIN,W%_PRED,VEGAS_PRED,HOME_TEAM_BEATS_SPREAD
0,0,2019-04-10,21801220,2018,1610612737,0.354,1610612754,0.585,-5.25,0,-1.0,0,1,0
1,1,2019-04-10,21801221,2018,1610612751,0.512,1610612748,0.476,-4.58,1,19.0,1,1,1
2,2,2019-04-10,21801222,2018,1610612766,0.476,1610612753,0.512,-3.50,0,-8.0,0,1,0
3,3,2019-04-10,21801223,2018,1610612752,0.207,1610612765,0.500,8.58,0,-26.0,0,0,0
4,4,2019-04-10,21801224,2018,1610612755,0.622,1610612741,0.268,-6.42,1,16.0,1,1,1
5,5,2019-04-10,21801225,2018,1610612763,0.402,1610612744,0.695,5.42,1,15.0,0,0,1
6,6,2019-04-10,21801226,2018,1610612749,0.732,1610612760,0.598,4.08,0,-11.0,1,0,0
7,7,2019-04-10,21801227,2018,1610612759,0.585,1610612742,0.402,-14.00,1,11.0,1,1,0
8,8,2019-04-10,21801228,2018,1610612743,0.659,1610612750,0.439,-12.67,1,4.0,1,1,0
9,9,2019-04-10,21801229,2018,1610612746,0.585,1610612762,0.610,-7.33,1,6.0,0,1,0
10,10,2019-04-10,21801230,2018,1610612757,0.646,1610612758,0.476,-3.67,1,5.0,1,1,1
11,11,2019-04-09,21801209,2018,1610612739,0.232,1610612766,0.481,8.25,0,-27.0,0,0,0
12,12,2019-04-09,21801210,2018,1610612765,0.494,1610612763,0.395,-11.25,1,7.0,1,1,0
13,13,2019-04-09,21801211,2018,1610612764,0.390,1610612738,0.598,-5.00,0,-6.0,0,1,0
14,14,2019-04-09,21801212,2018,1610612748,0.481,1610612755,0.617,-5.92,1,23.0,0,1,1
15,15,2019-04-09,21801213,2018,1610612741,0.272,1610612752,0.210,-1.83,0,-10.0,1,1,0
16,16,2019-04-09,21801214,2018,1610612750,0.444,1610612761,0.707,7.33,0,-20.0,0,0,0
17,17,2019-04-09,21801215,2018,1610612740,0.402,1610612744,0.704,9.67,0,-9.0,0,0,1
18,18,2019-04-09,21801216,2018,1610612742,0.407,1610612756,0.232,-8.33,1,11.0,1,1,1
19,19,2019-04-09,21801217,2018,1610612762,0.617,1610612743,0.654,-2.08,1,10.0,0,1,1
20,20,2019-04-09,21801218,2018,1610612760,0.593,1610612745,0.646,2.75,1,1.0,0,0,1
21,21,2019-04-09,21801219,2018,1610612747,0.451,1610612757,0.642,9.67,0,-3.0,0,0,1
22,22,2019-04-07,21801195,2018,1610612761,0.704,1610612748,0.475,-5.58,1,8.0,1,1,1
23,23,2019-04-07,21801196,2018,1610612739,0.235,1610612759,0.580,8.67,0,-22.0,0,0,0
24,24,2019-04-07,21801197,2018,1610612750,0.450,1610612760,0.588,6.25,0,-6.0,0,0,1
25,25,2019-04-07,21801198,2018,1610612765,0.488,1610612766,0.475,-6.58,0,-13.0,1,1,0
26,26,2019-04-07,21801199,2018,1610612754,0.580,1610612751,0.506,-2.92,0,-12.0,1,1,0
27,27,2019-04-07,21801201,2018,1610612763,0.400,1610612742,0.400,0.50,0,-2.0,1,0,0
28,28,2019-04-07,21801200,2018,1610612745,0.654,1610612756,0.235,-18.50,1,36.0,1,1,1
29,29,2019-04-07,21801202,2018,1610612749,0.741,1610612737,0.358,-11.33,1,8.0,1,1,0
30,30,2019-04-07,21801203,2018,1610612738,0.593,1610612753,0.506,-4.17,0,-8.0,1,1,0
31,31,2019-04-07,21801204,2018,1610612752,0.200,1610612764,0.395,4.00,1,3.0,0,0,1
32,32,2019-04-07,21801205,2018,1610612744,0.700,1610612746,0.580,-11.08,1,27.0,1,1,1
33,33,2019-04-07,21801206,2018,1610612757,0.638,1610612743,0.663,-7.42,1,7.0,0,1,0
34,34,2019-04-07,21801207,2018,1610612758,0.481,1610612740,0.407,-11.42,0,-4.0,1,1,0
35,35,2019-04-07,21801208,2018,1610612747,0.457,1610612762,0.613,11.92,1,4.0,0,0,1
36,36,2019-04-06,21801193,2018,1610612749,0.738,1610612751,0.500,-4.00,0,-5.0,1,1,0
37,37,2019-04-06,21801194,2018,1610612741,0.275,1610612755,0.625,10.08,0,-20.0,0,0,0
38,38,2019-04-05,21801180,2018,1610612766,0.468,1610612761,0.700,5.75,1,2.0,0,0,1
39,39,2019-04-05,21801181,2018,1610612753,0.500,1610612737,0.363,-8.75,1,36.0,1,1,1
40,40,2019-04-05,21801182,2018,1610612764,0.400,1610612759,0.575,6.50,0,-17.0,0,0,0
41,41,2019-04-05,21801183,2018,1610612754,0.588,1610612738,0.600,1.25,0,-20.0,0,0,0
42,42,2019-04-05,21801184,2018,1610612745,0.650,1610612752,0.190,-17.92,1,24.0,1,1,1
43,43,2019-04-05,21801185,2018,1610612750,0.456,1610612748,0.481,3.67,1,2.0,0,0,1
44,44,2019-04-05,21801186,2018,1610612760,0.582,1610612765,0.494,-6.40,1,13.0,1,1,1
45,45,2019-04-05,21801187,2018,1610612742,0.392,1610612763,0.405,-4.00,0,-10.0,0,1,0
46,46,2019-04-05,21801188,2018,1610612762,0.620,1610612758,0.488,-10.08,1,21.0,1,1,1
47,47,2019-04-05,21801189,2018,1610612756,0.238,1610612740,0.400,2.50,1,7.0,0,0,1
48,48,2019-04-05,21801190,2018,1610612743,0.671,1610612757,0.633,-6.20,1,9.0,1,1,1
49,49,2019-04-05,21801191,2018,1610612744,0.696,1610612739,0.238,-16.00,1,6.0,1,1,0

In [9]:
y_actual = df['HOME_TEAM_BEATS_SPREAD']
y_pred_algo = df['W%_PRED']

# confusion matrix
print(confusion_matrix(y_actual, y_pred_algo))

# accuracy: (tp + tn) / (p + n)
print('Accuracy: %f' % accuracy_score(y_actual, y_pred_algo))

# precision tp / (tp + fp)
print('Precision: %f' % precision_score(y_actual, y_pred_algo))

# recall: tp / (tp + fn)
print('Recall: %f' % recall_score(y_actual, y_pred_algo))

[[2302 2062]
 [1833 2405]]
Accuracy: 0.547198
Precision: 0.538393
Recall: 0.567485